### ISSUE TITLE
新增上好運banner簡體中文版

### ISSUE THREAD

**Issue by FangjieHung** [degather/bootcamp-gitflow#17]
六種主題Ｘ兩種語系

- [ ] 上好運情義相挺

- [ ] 一生一次

- [ ] 桃園三結義

- [ ] 萬里送千金

- [ ] 贏家通殺

- [ ] 週二正午搶搶搶

**Comment by liorwen** [comment]
那就請 @FangjieHung @oliviayu0411 協助處理此項目

**Comment by FangjieHung** [comment]
已完成，請查看#18
